from app.models import SQLQuery


class SQLGenerator:
    def generate(
        self,
        question: str,
        schema: dict,
    ) -> SQLQuery:
        question_lower = question.lower()

        if "revenue" in question_lower and "status" in question_lower:
            return SQLQuery(
                query=(
                    "SELECT status, SUM(amount) AS total_revenue "
                    "FROM orders "
                    "GROUP BY status"
                ),
                purpose="Calculate total revenue grouped by order status.",
            )

        if "revenue" in question_lower and "customer" in question_lower:
            return SQLQuery(
                query=(
                    "SELECT c.name, SUM(o.amount) AS total_revenue "
                    "FROM customers c "
                    "JOIN orders o ON c.id = o.customer_id "
                    "GROUP BY c.id, c.name "
                    "ORDER BY total_revenue DESC"
                ),
                purpose="Calculate total revenue generated by each customer.",
            )

        if "orders" in question_lower and "status" in question_lower:
            return SQLQuery(
                query=(
                    "SELECT status, COUNT(*) AS order_count "
                    "FROM orders "
                    "GROUP BY status"
                ),
                purpose="Count orders grouped by their status.",
            )

        raise ValueError(
            "The current SQL generator does not know how to answer this question."
        )