from app.models import QueryResult, SQLQuery


class SQLGenerator:
    def generate(
        self,
        question: str,
        schema: dict,
        previous_results: list[QueryResult],
    ) -> SQLQuery:
        question_lower = question.lower()

        if not previous_results:
            if "revenue" in question_lower and "status" in question_lower:
                return SQLQuery(
                    query=(
                        "SELECT status, SUM(amount) AS total_revenue "
                        "FROM orders "
                        "GROUP BY status"
                    ),
                    purpose="Calculate total revenue grouped by order status.",
                )

            if "revenue" in question_lower and "customer" in question_lower:
                return SQLQuery(
                    query=(
                        "SELECT c.name, SUM(o.amount) AS total_revenue "
                        "FROM customers c "
                        "JOIN orders o ON c.id = o.customer_id "
                        "GROUP BY c.id, c.name "
                        "ORDER BY total_revenue DESC"
                    ),
                    purpose="Calculate total revenue generated by each customer.",
                )

            if "orders" in question_lower and "status" in question_lower:
                return SQLQuery(
                    query=(
                        "SELECT status, COUNT(*) AS order_count "
                        "FROM orders "
                        "GROUP BY status"
                    ),
                    purpose="Count orders grouped by their status.",
                )

        if (
            "revenue" in question_lower
            and "status" in question_lower
            and previous_results
        ):
            return SQLQuery(
                query=(
                    "SELECT status, COUNT(*) AS order_count, "
                    "SUM(amount) AS total_revenue, "
                    "AVG(amount) AS average_order_value "
                    "FROM orders "
                    "GROUP BY status"
                ),
                purpose=(
                    "Investigate order count and average order value "
                    "for each status."
                ),
            )

        raise ValueError(
            "The current SQL generator does not know how to answer this question."
        )